#
#  Copyright (C) 2019 F. Hoffmann-La Roche Ltd
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

writeSVMModel <- function( folderPath, model, trainingSet, scaling=NULL ) {
  #
  #  Writes an SVM model to a libSVM format
  #
  #  The model must have been generated by the e1071 package (i.e. it doesn't work with SVMs from the Caret package)
  #
  #  Args:
  #    folderPath: the folder which the mode is written to (with name 'svmModel.svm')
  #    model: a model of class anchorlda
  #    additionalCoefficient: if non-NULL, an additional coefficient in the form list(featureName=string,coefficient=double)
  #    scaling: if non-NULL scaling data is read from this dataframe (first column = mean, second column = scale), otherwise from the SVM model
  #
  #  Returns:
  #    none
  #
  filePathSVM = 'svmModel.svm';
  pathOut = paste(folderPath,"\\",filePathSVM,sep='');
  
  filePathScale = 'svmModel.scale';
  pathOutScale = paste(folderPath,"\\",filePathScale,sep='');
  
  filePathFeatures = "svmModel.features";
  pathOutFeatures = paste(folderPath,"\\",filePathFeatures,sep='');
  
  colNames = colnames( trainingSet$featuresTraining );
  
  fileConn<-file(pathOutFeatures)
  writeLines(colNames, fileConn)
  close(fileConn)
  
  featureNames = colnames( trainingSet$featuresTraining );

  if (is.null(scaling)) {
    write.svm( model, svm.file=pathOut, scale.file=pathOutScale );
  } else {
    write.svm( model, svm.file=pathOut );
    
    scalingIndices = match( featureNames, rownames(scaling) );
    
    scalingToSave = scaling[scalingIndices,];
    
    write.table( scalingToSave, file=pathOutScale, sep=' ', row.names=FALSE, col.names=FALSE );
  }
}